import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Badar Expo Solutions',
  description: 'Generated by AMK',
  manifest: "/manifest.json",
  icons: {
    icon: [
      { url: '/icons/Badar-icon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/icons/Badar-icon-32x32.png', sizes: '32x32', type: 'image/png' },
      { url: '/icons/Badar-icon-72x72.png', sizes: '72x72', type: 'image/png' },
      { url: '/icons/Badar-icon-96x96.png', sizes: '96x96', type: 'image/png' },
      { url: '/icons/Badar-icon-144x144.png', sizes: '144x144', type: 'image/png' },
      { url: '/icons/Badar-icon-152x152.png', sizes: '152x152', type: 'image/png' },
      { url: '/icons/Badar-icon-192x192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icons/Badar-icon-512x512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: [
      { url: '/icons/Badar-icon-96x96.png', sizes: '180x180', type: 'image/png' },
    ],
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
